services:
  fastapi_service:
    build: .
    container_name: fastapi_container
    ports:
      - 8000:8000
    
    environment:
      - DATABASE_HOSTNAME=postgres_service
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=12345
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60

  postgres_service:
    image: postgres
    container_name: postgres_container
    environment:
      - POSTGRES_PASSWORD=12345

    ports:
      - 5432:5432

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: