services:
  fastapi_service:
    # build: .
    image: sanaullahaq/fastapi-prod
    container_name: fastapi_container
    ports:
      - 80:8000
    # volumes:
    #   - ./:/usr/src/app:ro
    environment:
      # - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_HOSTNAME=postgres_service
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    # command: >
      # sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    command: alembic upgrade head
    depends_on:
      - postgres_service

  postgres_service:
    image: postgres
    container_name: postgres_container
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER = ${DATABASE_USERNAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
  
volumes:
  postgres-db: