"""auto-generate-vote-table-with-alembic

Revision ID: 4e646ceb821c
Revises: 577f353d4990
Create Date: 2024-09-01 18:15:59.919734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e646ceb821c'
down_revision: Union[str, None] = '577f353d4990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    # ### end Alembic commands ###

    """
    autogenerated codes can be generated with below cmd and this codes are generated
    based on the gap of models class and the current db state,
    alembic can check our models as we hava given that permission to alembic with
    `target_metadata = Base.metadata` in the env.py file of the alembic
    alembic revision --autogenerate -m "auto-generate-vote-table-with-alembic"
    """


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
