name: Build and Deploy Code  # Name of the workflow

on:  # Triggers for the workflow
    - push  # Trigger on push to the repository
    - pull_request  # Trigger on pull request events

jobs:  # Define the jobs to be executed
    job1:  # Job identifier
        env:
          DATABASE_HOSTNAME: localhost
          DATABASE_PORT: 5432
          DATABASE_PASSWORD: 12345
          DATABASE_NAME: fastapi
          DATABASE_USERNAME: postgres
          SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 60

        runs-on: ubuntu-latest  # Specify the environment to run the job
        steps:  # Define the steps for the job
            - name: pulling git repo  # Step to check out the repository
              uses: actions/checkout@v4  # Use the checkout action to pull the code

            - name: install Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: check installed python version
              run: python --version

            - name: update pip
              run: python -m pip install --upgrade pip

            - name: install dependencies
              run: pip install -r req.txt

            - name: test with pytest
              run: |  # run multiple cmd's on a single run
                pip install pytest
                pytest